ipAddr: 127.0.0.1
server:
  port: 9020
spring:
  datasource:
    username: luna
    password: luna
    url: jdbc:mysql://${ipAddr}:3306/mall-ums?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${ipAddr}:8848
    sentinel:
      transport:
        dashboard: ${ipAddr}:8333
  application:
    name: mall-member
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: ${ipAddr}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

