ipAddr: 127.0.0.1
server:
  port: 9010
spring:
  datasource:
    username: luna
    password: luna
    url: jdbc:mysql://${ipAddr}:3306/mall-sms?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${ipAddr}:8848
    sentinel:
      transport:
        dashboard: ${ipAddr}:8333
  application:
    name: mall-coupon
  zipkin:
    base-url: ${ipAddr}:9411/
    # 关闭我们自动的服务发现功能
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

